Repository mokumoku-lovers/moku-moku-cards, pull requests merged in 2022-02, with the labels that each got.

#20 Feature/get decks endpoint/14
  app/url_mappings.go
  controllers/decks/DeckController.go
  domain/decks/deck_dao.go
  domain/decks/deck_dto.go
  services/DeckService.go
Labels: enhancement, task

#19 Feat/16/post card
  app/url_mappings.go
  controllers/cards/CardController.go
  domain/cards/card_dao.go
  domain/cards/card_dto.go
  services/CardService.go
Labels: enhancement, task

#25 Feat/22/put deck
  app/url_mappings.go
  controllers/decks/DeckController.go
  domain/decks/deck_dao.go
  services/DeckService.go
  utils/docs/toDoc.go
Labels: enhancement, DB

#24 Feat/15/post deck (Discussion needed)
  app/url_mappings.go
  controllers/decks/DeckController.go
  domain/decks/deck_dao.go
  domain/decks/deck_dto.go
  services/DeckService.go
  utils/docs/toDoc.go
Labels: enhancement, help wanted, DB, fix

#26 Feat/23/get deck creator
  app/url_mappings.go
  controllers/decks/DeckController.go
  domain/decks/deck_dao.go
  services/DeckService.go
Labels: enhancement, task, DB

#27 Feat/delete deck/21
  app/url_mappings.go
  controllers/decks/DeckController.go
  domain/decks/deck_dao.go
  services/DeckService.go
Labels: enhancement, task, DB
